version: '3'
services:
  postgres:
    build: postgres
    image: postgres:15
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    networks:
      - postgres_net
networks:
  postgres_net: